// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package account

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/jackjohn7/smllnk/public/views/layout"
import "github.com/jackjohn7/smllnk/public/views/utils"

func AccountTemplate(baseProps layout.BaseProps) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col w-screen items-center\"><div class=\"w-[50%] flex flex-col space-y-8\"><h1 class=\"text-white text-3xl text-center font-inter\">Welcome, ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(baseProps.AuthCtx.User.Email)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `public/views/account/page.templ`, Line: 9, Col: 102}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><dialog id=\"account-deletion-dialog\" class=\"bg-up-1 rounded-lg p-2 m-t-12\"><div class=\"flex flex-col space-y-4\"><h1 class=\"text-white font-bold text-3xl\">Notice</h1><p class=\"text-white font-inter\">Deleting your account is permanent. All data related to your account will be removed from our database.</p><div class=\"flex flex-row justify-between\"><button type=\"button\" class=\"font-inter btn btn-green\">Cancel</button><form action=\"/accounts/delete\" method=\"POST\" class=\"m-0\"><button type=\"submit\" class=\"btn bg-red-400 font-inter font-bold\">Delete Account</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = utils.CsrfHelper(baseProps.CsrfToken).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</form></div></div></dialog><section id=\"links\"><h2 class=\"text-white text-2xl font-inter\">Links</h2><p class=\"font-inter text-white\">Your links have been clicked 100 times.</p></section><section id=\"account-deletion\"><h2 class=\"text-red-400 text-2xl font-inter\">Actions</h2><p class=\"text-white font-inter\">If you no longer wish to utilize SmlLnk, you can delete your account along  with all of your links. Doing so is irreversible. SmlLnk respects your  right to be forgotten should you choose to be.</p><script>\n            function openDialog() {\n              // dialog\n              let dialog = document.getElementById(\"account-deletion-dialog\");\n              dialog.showModal();\n            }\n          </script><button onclick=\"openDialog()\" class=\"btn bg-red-400 font-bold font-inter\" type=\"button\">Delete Account</button></section></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base(baseProps).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
